[project]
name = "lesson-08-code-review"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "GiteaImp", email = "admin@impresaltd.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
lesson-08-code-review = "lesson_08_code_review:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
